# Generated by Django 5.0.2 on 2025-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='150 characters or fewer. Letters, digits, spaces and @/./+/-/_ allowed.', max_length=150, null=True),
        ),
    ]
